#!/usr/bin/env python3
"""
Page builder for everything beyond the Home page.

The site has no build step and none is being introduced: this script is a
tool, not a dependency. It writes plain .html files that stand on their own,
and it exists for one reason — the Work with Experts, Share Your Feedback and
footer sections have to be *the same* on every page. Rather than paste them
into twenty files and watch them drift, the script lifts them out of
hero-full.html at build time, so Home stays the single source for them.

Run it from the site directory after changing Home or the page data below:

    python3 build-pages.py

Content here is placeholder, pending the SEO team's copy.
"""

import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
HOME = ROOT / 'hero-full.html'

# --------------------------------------------------------------------------
# Lifting the shared sections out of Home
# --------------------------------------------------------------------------


def block(source, start, end):
    """Return source[start .. end] inclusive, by literal markers."""
    i = source.index(start)
    j = source.index(end, i) + len(end)
    return source[i:j]


def load_partials():
    src = HOME.read_text(encoding='utf-8')
    nav = block(src, '<header class="nav">', '</header>')
    # the nav sits eight spaces deep inside the hero; the shell below puts it
    # at six, so pull the whole block left by two
    nav = '\n'.join(line[2:] if line.startswith('  ') else line for line in nav.split('\n'))
    return {
        'nav': nav,
        'expert_cta': block(src, '<section class="expert-cta" id="consultation-form">', '\n  </section>'),
        'feedback': block(src, '<section class="feedback" id="feedback">', '\n  </section>'),
        'footer': block(src, '<footer class="footer">', '\n  </footer>'),
    }


def nav_for_page(nav, has_consultation):
    """Point the Home page's in-page anchors at Home when we're not on it."""
    nav = nav.replace('<a href="/" class="nav__logo">', '<a href="hero-full.html" class="nav__logo">')
    nav = nav.replace('href="#services" class="nav__link nav__link--dropdown"',
                      'href="services.html" class="nav__link nav__link--dropdown"')
    nav = nav.replace('<a href="#reviews" class="nav__link">',
                      '<a href="hero-full.html#reviews" class="nav__link">')
    if not has_consultation:
        nav = nav.replace('<a href="#consultation" class="btn btn--panel">',
                          '<a href="hero-full.html#consultation" class="btn btn--panel">')
    return nav


def footer_for_page(footer):
    """The footer's one in-page anchor is the services section on Home."""
    return footer.replace('href="hero-full.html#services"', 'href="hero-full.html#services"')


# --------------------------------------------------------------------------
# Page shell
# --------------------------------------------------------------------------

FONTS = (
    '  <link rel="preconnect" href="https://fonts.googleapis.com" />\n'
    '  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />\n'
    '  <link\n'
    '    href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;1,500'
    '&family=Plus+Jakarta+Sans:wght@300;400;500;600;700&family=Noto+Sans+Arabic:wght@400;500;600;700'
    '&family=Noto+Serif+Devanagari:wght@400;500&display=swap"\n'
    '    rel="stylesheet"\n'
    '  />'
)

# Applied before first paint. The shade on Home is the only theme control on
# the site; this is how its choice reaches a page that has no shade.
THEME_BOOT = '''  <script>
    try {
      if (window.localStorage.getItem('hof-theme') === 'dark') {
        document.documentElement.classList.add('is-dark');
      }
    } catch (e) {}
  </script>'''

BASE_CSS = ['styles-hero-full.css', 'page.css']
TAIL_CSS = ['cta-banner.css', 'callback-form.css', 'feedback.css', 'footer.css',
            'dark-mode.css', 'page-dark.css', 'rtl.css']

BASE_JS = ['nav-menu.js', 'i18n.js', 'page.js']


def shell(*, title, description, body_class, css, js, band, main, partials,
          sections=('expert_cta', 'feedback')):
    sheets = '\n'.join(f'  <link rel="stylesheet" href="{href}" />'
                       for href in BASE_CSS + css + TAIL_CSS)
    scripts = '\n'.join(f'  <script src="{src}"></script>' for src in BASE_JS + js)
    tail = '\n\n'.join('  ' + partials[name].strip() for name in sections)
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title}</title>
  <meta name="description" content="{description}" />

{FONTS}

{sheets}

{THEME_BOOT}
</head>
<body class="{body_class}">

  <!-- Generated by build-pages.py — edit the data in that script, not this
       file, or the next build will write over you. -->

  <div class="page-band">
    <div class="page-band__inner">
{band}
    </div>
  </div>

{main}

{tail}

  {partials['footer'].strip()}

{scripts}
</body>
</html>
'''


def crumbs(trail):
    """trail: [(label, href), ..., (label, None)] — the last is the page."""
    out = ['      <nav class="crumbs" aria-label="Breadcrumb">']
    for i, (label, href) in enumerate(trail):
        if i:
            out.append('        <span class="crumbs__sep" aria-hidden="true">/</span>')
        if href:
            out.append(f'        <a href="{href}">{label}</a>')
        else:
            out.append(f'        <span aria-current="page">{label}</span>')
    out.append('      </nav>')
    return '\n'.join(out)


def page_head(*, eyebrow, title, lede, chips=()):
    out = ['      <div class="page-head">',
           f'        <span class="page-head__eyebrow">{eyebrow}</span>',
           f'        <h1 class="page-head__title">{title}</h1>',
           f'        <p class="page-head__lede">{lede}</p>']
    if chips:
        out.append('        <div class="page-head__meta">')
        for chip in chips:
            out.append(f'          <span class="page-head__chip">{chip}</span>')
        out.append('        </div>')
    out.append('      </div>')
    return '\n'.join(out)


def block_head(num, title, note):
    return (f'        <div class="block-head reveal">\n'
            f'          <span class="block-head__num">{num}</span>\n'
            f'          <h2 class="block-head__title">{title}</h2>\n'
            f'          <p class="block-head__note">{note}</p>\n'
            f'        </div>')


# --------------------------------------------------------------------------
# Services — data
#
# accent / tint are the card colours the Home page already uses, so a service
# keeps the same identity from the card through to its page.
# --------------------------------------------------------------------------

SERVICES = [
    {
        'slug': 'service-skilled-migration',
        'nav_name': 'Skilled Migration',
        'title': 'Skilled Migration Canada &amp; Australia',
        'short': 'Skilled Migration',
        'accent': '#0095ff',
        'tint': '#dfedf7',
        'image': 'assets/services-v2/skilled-migration.jpg',
        'alt': 'Toronto skyline, Canada',
        'plate': ('Canada &amp; Australia', 'Two points-tested systems, two very different strategies'),
        'lede': ('Both countries choose skilled migrants by points, and both change the pass mark '
                 'as their labour market moves. The work is in reading your profile honestly, then '
                 'picking the program and the province where your score is actually competitive.'),
        'chips': ['Points-tested', 'Permanent residence', 'Family included'],
        'card_text': ('Express Entry, Provincial Nominee Programs and the Australian skilled '
                      'subclasses — assessed against your real score, not a brochure.'),
        'groups': [
            {'code': 'CA', 'name': 'Canada', 'nodes': [
                ('Express Entry', 'The federal pool. Three programs are ranked together on one CRS score, and rounds are drawn every two weeks.', 'FSW · CEC · FST'),
                ('Provincial Nominee Program', 'A province nominates you against its own shortage list. A nomination adds 600 points and effectively guarantees an invitation.', '11 provinces'),
                ('Atlantic Immigration Program', 'Employer-driven route into New Brunswick, Nova Scotia, PEI and Newfoundland, with no points test.', 'Employer-led'),
            ]},
            {'code': 'AU', 'name': 'Australia', 'nodes': [
                ('Skilled Independent', 'Permanent from day one, no sponsor and no state tie. The hardest of the three to score into.', 'Subclass 189'),
                ('Skilled Nominated', 'A state or territory nominates you and adds five points; you commit to living there.', 'Subclass 190'),
                ('Skilled Work Regional', 'Five-year provisional visa in designated regional areas, with a defined path to permanence.', 'Subclass 491'),
            ]},
        ],
        'types': [
            ('FSW', 'Federal Skilled Worker', 'The main Express Entry program for applicants with foreign work experience and no Canadian job offer. Your CRS score decides everything.',
             [('Route', 'Express Entry'), ('Decides', 'CRS score'), ('Outcome', 'Permanent residence')]),
            ('CEC', 'Canadian Experience Class', 'For applicants who already hold skilled Canadian work experience. Lower language thresholds and no proof-of-funds requirement.',
             [('Requires', '1 year in Canada'), ('Route', 'Express Entry'), ('Outcome', 'Permanent residence')]),
            ('PNP', 'Provincial Nominee Program', 'Each province runs its own streams against its own shortages. Some draw directly from the Express Entry pool, others accept applications on their own.',
             [('Adds', '600 CRS points'), ('Tie', 'Province of nomination'), ('Outcome', 'Permanent residence')]),
            ('189', 'Skilled Independent', 'Australia&rsquo;s unsponsored points-tested visa. Permanent on grant, with no obligation to live in any particular state.',
             [('Minimum', '65 points'), ('Sponsor', 'None'), ('Outcome', 'Permanent residence')]),
            ('190', 'Skilled Nominated', 'State-nominated permanent visa. The nomination adds five points and usually requires your occupation to be on that state&rsquo;s list.',
             [('Adds', '5 points'), ('Commitment', 'Nominating state'), ('Outcome', 'Permanent residence')]),
            ('491', 'Skilled Work Regional', 'Provisional visa for designated regional areas, sponsored by a state or an eligible relative, convertible after three years.',
             [('Adds', '15 points'), ('Valid', '5 years'), ('Then', 'Subclass 191')]),
        ],
    },
    {
        'slug': 'service-study-abroad',
        'nav_name': 'Study Abroad',
        'title': 'Study Abroad &amp; Student Visas',
        'short': 'Study Abroad',
        'accent': '#ff5900',
        'tint': '#f7e9df',
        'image': 'assets/services-v2/study-abroad.jpg',
        'alt': 'Graduate in cap and gown',
        'plate': ('Five study destinations', 'Course, institution and visa chosen as one decision'),
        'lede': ('A student visa is granted on the strength of the study plan behind it. We work '
                 'backwards from where you want to end up — the course, the institution and the '
                 'post-study work rights that follow it — and only then file the visa.'),
        'chips': ['Course selection', 'Post-study work', 'Dependants where allowed'],
        'card_text': ('Australia, the UK, Canada, Germany and the USA — with the post-study work '
                      'route mapped before the application is filed.'),
        'groups': [
            {'code': 'AU', 'name': 'Australia', 'nodes': [
                ('Student Visa', 'Covers the full length of the course, with work rights during study and a graduate route after it.', 'Subclass 500'),
                ('Temporary Graduate', 'Post-study work visa, with the length tied to the qualification held.', 'Subclass 485'),
            ]},
            {'code': 'UK', 'name': 'United Kingdom', 'nodes': [
                ('Student Visa', 'Sponsored by a licensed institution through a CAS, with maintenance funds held for 28 days.', 'CAS required'),
                ('Graduate Route', 'Two years of unsponsored work after a UK degree, three after a doctorate.', '2–3 years'),
            ]},
            {'code': 'CA', 'name': 'Canada', 'nodes': [
                ('Study Permit', 'Requires a provincial attestation letter and a designated learning institution.', 'PAL required'),
                ('Post-Graduation Work Permit', 'Up to three years of open work, and the usual bridge into Canadian Experience Class.', 'Up to 3 years'),
            ]},
            {'code': 'DE', 'name': 'Germany', 'nodes': [
                ('National Student Visa', 'Type D visa against a blocked account, converted to a residence permit after arrival.', 'Type D'),
            ]},
            {'code': 'US', 'name': 'United States', 'nodes': [
                ('F-1 Student Visa', 'Issued on an I-20 from a SEVP-certified school, with the interview as the real hurdle.', 'I-20 · SEVIS'),
            ]},
        ],
        'types': [
            ('500', 'Australia Student Visa', 'Granted for the duration of the course. Work rights apply during study, and the Genuine Student requirement means the study plan has to hold together.',
             [('Work', '48 hrs / fortnight'), ('Family', 'Dependants allowed'), ('Then', 'Subclass 485')]),
            ('485', 'Temporary Graduate Visa', 'Post-study work rights for graduates of Australian institutions, with the term set by the level of qualification.',
             [('Valid', '2–4 years'), ('Work', 'Unrestricted'), ('Route', 'Post-study')]),
            ('UK', 'UK Student Visa', 'Sponsored study at a licensed institution. Maintenance funds must be held for 28 consecutive days before the application.',
             [('Sponsor', 'CAS'), ('Funds', '28-day rule'), ('Then', 'Graduate Route')]),
            ('CA', 'Canada Study Permit', 'Requires an acceptance letter from a designated learning institution and, in most provinces, an attestation letter.',
             [('Work', '24 hrs / week'), ('Family', 'Spouse may work'), ('Then', 'PGWP')]),
            ('DE', 'Germany Student Visa', 'Entry visa against proof of funds in a blocked account, exchanged for a residence permit once you have registered locally.',
             [('Funds', 'Blocked account'), ('Tuition', 'Public: minimal'), ('Then', 'Job-seeker permit')]),
            ('F-1', 'United States F-1', 'Academic study on an I-20. Optional Practical Training follows the degree, extended for STEM fields.',
             [('Work', 'On-campus'), ('After', 'OPT 12 months'), ('STEM', '+24 months')]),
        ],
    },
    {
        'slug': 'service-family-sponsorship',
        'nav_name': 'Family Sponsorship',
        'title': 'Family Sponsorship &amp; Reunification',
        'short': 'Family Sponsorship',
        'accent': '#179b66',
        'tint': '#f0f9f4',
        'image': 'assets/services-v2/family-sponsorship.jpg',
        'alt': 'Family portrait outdoors',
        'plate': ('Bringing family together', 'Relationship evidence, prepared properly, decides these cases'),
        'lede': ('Family cases are not won on forms. They are won on evidence of a relationship '
                 'that a stranger can follow — which is the part most applicants under-prepare '
                 'and the part we spend the most time on.'),
        'chips': ['Spouse &amp; partner', 'Parents', 'Dependent children'],
        'card_text': ('Spouse, parent and child sponsorship for Canada and Australia, built around '
                      'the relationship evidence these cases actually turn on.'),
        'groups': [
            {'code': 'CA', 'name': 'Canada', 'nodes': [
                ('Spouse or Partner', 'Inland or outland sponsorship for a spouse, common-law or conjugal partner, with an open work permit available inland.', 'Inland · Outland'),
                ('Parents &amp; Grandparents', 'Interest-to-sponsor pool with an annual intake, plus the super visa as the standing alternative.', 'Annual intake'),
                ('Dependent Children', 'Sponsorship of children under 22 who are not married or in a common-law relationship.', 'Under 22'),
            ]},
            {'code': 'AU', 'name': 'Australia', 'nodes': [
                ('Partner Visa', 'Two-stage visa — provisional, then permanent two years later, filed onshore or offshore.', '820/801 · 309/100'),
                ('Parent Visa', 'Queued non-contributory stream or the far shorter contributory stream at a much higher cost.', '103 · 143'),
                ('Child Visa', 'For a dependent child of an Australian citizen, permanent resident or eligible New Zealand citizen.', '101 · 802'),
            ]},
        ],
        'types': [
            ('CA', 'Spousal Sponsorship (Canada)', 'Outland applications are processed by a visa office abroad; inland applications allow an open work permit while you wait, but restrict travel.',
             [('Undertaking', '3 years'), ('Inland', 'Open work permit'), ('Outcome', 'Permanent residence')]),
            ('PGP', 'Parents &amp; Grandparents', 'Invitations are drawn from an interest-to-sponsor pool. Income has to be met for three consecutive tax years.',
             [('Income', '3 tax years'), ('Undertaking', '20 years'), ('Alt', 'Super visa')]),
            ('DC', 'Dependent Child', 'Straightforward where custody is clear; the complications are almost always consent from a second parent.',
             [('Age', 'Under 22'), ('Needs', 'Custody proof'), ('Outcome', 'Permanent residence')]),
            ('820', 'Partner Visa (Australia)', 'Granted provisionally first, then assessed again for permanence two years on. The same relationship evidence carries both stages.',
             [('Stage 1', 'Provisional'), ('Stage 2', '+2 years'), ('Work', 'Full rights')]),
            ('143', 'Contributory Parent Visa', 'Substantially faster than the non-contributory queue, at a substantially higher contribution to health costs.',
             [('Queue', 'Shorter'), ('Cost', 'Higher'), ('Outcome', 'Permanent residence')]),
            ('101', 'Child Visa (Australia)', 'Permanent visa for a dependent child, filed offshore, with onshore equivalents where the child is already in Australia.',
             [('Filed', 'Offshore'), ('Onshore', 'Subclass 802'), ('Outcome', 'Permanent residence')]),
        ],
    },
    {
        'slug': 'service-usa-visas',
        'nav_name': 'U.S. NIW &amp; Investor',
        'title': 'U.S. NIW &amp; Investor Visas',
        'short': 'U.S. NIW &amp; Investor',
        'accent': '#6b81cf',
        'tint': '#ecf1ff',
        'image': 'assets/services-v2/usa-visas.jpg',
        'alt': 'Statue of Liberty, USA',
        'plate': ('United States', 'Petition-led cases, won on the quality of the argument'),
        'lede': ('These are petitions, not applications. What decides them is the evidence file '
                 'and the argument built on top of it — which is why they are drafted like a case '
                 'rather than filled in like a form.'),
        'chips': ['Self-petition', 'Investor routes', 'Intra-company transfer'],
        'card_text': ('EB-2 National Interest Waiver petitions, treaty investor routes and '
                      'intra-company transfers, prepared as evidence-led cases.'),
        'groups': [
            {'code': 'EB', 'name': 'Employment-based petitions', 'nodes': [
                ('EB-2 National Interest Waiver', 'Self-petition that waives the job offer and labour certification, argued on the national importance of your work.', 'No employer needed'),
                ('EB-1A Extraordinary Ability', 'For applicants at the top of their field, evidenced against a defined set of criteria.', 'Priority category'),
            ]},
            {'code': 'IN', 'name': 'Investor &amp; business', 'nodes': [
                ('E-2 Treaty Investor', 'Non-immigrant visa for a substantial, at-risk investment in a real operating business, renewable indefinitely.', 'Treaty country'),
                ('EB-5 Immigrant Investor', 'Permanent residence through a qualifying investment and the creation of ten full-time jobs.', '10 jobs'),
            ]},
            {'code': 'L', 'name': 'Intra-company transfer', 'nodes': [
                ('L-1A Manager or Executive', 'Transfer into a US office of a related company, with a route to EB-1C permanence.', 'Up to 7 years'),
                ('L-1B Specialised Knowledge', 'Transfer for employees holding knowledge specific to the company&rsquo;s products or processes.', 'Up to 5 years'),
            ]},
        ],
        'types': [
            ('NIW', 'EB-2 National Interest Waiver', 'Three prongs decide it: substantial merit and national importance, whether you are well positioned to advance the work, and whether waiving the job offer benefits the United States.',
             [('Employer', 'Not required'), ('Basis', 'Three-prong test'), ('Outcome', 'Green card')]),
            ('EB-1A', 'Extraordinary Ability', 'Requires evidence against at least three of ten criteria, then a final merits assessment of the record as a whole.',
             [('Criteria', '3 of 10'), ('Employer', 'Not required'), ('Outcome', 'Green card')]),
            ('E-2', 'Treaty Investor', 'The investment must be substantial relative to the business, already at risk, and in a genuine enterprise rather than a holding of funds.',
             [('Nationality', 'Treaty country'), ('Renewal', 'Indefinite'), ('Family', 'Spouse may work')]),
            ('EB-5', 'Immigrant Investor', 'Direct investment or a regional centre project, conditional for two years before the conditions are removed.',
             [('Jobs', '10 full-time'), ('Conditional', '2 years'), ('Outcome', 'Green card')]),
            ('L-1A', 'Intra-company Manager', 'Requires a qualifying relationship between the foreign and US entity and a year of employment abroad in the last three.',
             [('Abroad', '1 of last 3 yrs'), ('Maximum', '7 years'), ('Then', 'EB-1C')]),
            ('L-1B', 'Specialised Knowledge', 'The evidential burden sits on showing knowledge that is genuinely specific to the employer, not merely advanced.',
             [('Abroad', '1 of last 3 yrs'), ('Maximum', '5 years'), ('Family', 'Spouse may work')]),
        ],
    },
    {
        'slug': 'service-europe-visas',
        'nav_name': 'Europe',
        'title': 'Europe Golden Visa &amp; Visitor Visas',
        'short': 'Europe',
        'accent': '#fd0148',
        'tint': '#ffe8ef',
        'image': 'assets/services-v2/europe-visas.jpg',
        'alt': 'Eiffel Tower, Paris',
        'plate': ('Europe', 'Residence by investment, by skill, or simply to visit'),
        'lede': ('Europe is not one system. Residence by investment, the skilled routes and a '
                 'short-stay Schengen visa are three different decisions with three different '
                 'standards of proof, and the right one depends on what you actually want.'),
        'chips': ['Residence by investment', 'EU Blue Card', 'Schengen short-stay'],
        'card_text': ('Golden visa programmes, the EU Blue Card and Schengen short-stay visas — '
                      'assessed on what residence is actually for.'),
        'groups': [
            {'code': 'RI', 'name': 'Residence by investment', 'nodes': [
                ('Portugal Golden Visa', 'Residence through qualifying investment, with a low physical-presence requirement and a route to citizenship.', 'Low stay days'),
                ('Greece Golden Visa', 'Residence permit against a property investment, renewable while the investment is held.', 'Property-based'),
                ('Malta Residence', 'Residence programme combining a contribution with a property requirement.', 'Contribution'),
            ]},
            {'code': 'SK', 'name': 'Work &amp; talent', 'nodes': [
                ('EU Blue Card', 'Skilled work permit tied to a qualifying salary and recognised qualifications, portable across most member states.', 'Salary threshold'),
                ('Germany Opportunity Card', 'Points-based job-seeker residence, allowing time in country to find qualifying work.', 'Points-based'),
            ]},
            {'code': 'C', 'name': 'Visitor', 'nodes': [
                ('Schengen Short-Stay', 'Up to 90 days in any 180 across the Schengen area, for tourism, family or business.', '90 / 180 days'),
            ]},
        ],
        'types': [
            ('PT', 'Portugal Golden Visa', 'Qualifying investment routes now centre on funds and business creation rather than residential property. Physical presence requirements stay light.',
             [('Stay', 'Low requirement'), ('Family', 'Included'), ('After', 'Citizenship route')]),
            ('GR', 'Greece Golden Visa', 'Property-based residence, with thresholds that vary by region. The permit runs as long as the investment is held.',
             [('Basis', 'Property'), ('Renewal', 'While held'), ('Family', 'Included')]),
            ('MT', 'Malta Residence', 'Combines a government contribution with a property lease or purchase, assessed through a formal due-diligence process.',
             [('Basis', 'Contribution'), ('Checks', 'Due diligence'), ('Family', 'Included')]),
            ('EU', 'EU Blue Card', 'Requires a recognised degree and a job offer above a salary threshold set by the member state. Portable after an initial period.',
             [('Needs', 'Job offer'), ('Salary', 'Threshold applies'), ('Then', 'Long-term residence')]),
            ('DE', 'Opportunity Card', 'Points-based residence that lets you enter Germany to look for qualifying work rather than arranging it first.',
             [('Basis', 'Points'), ('Purpose', 'Job search'), ('Then', 'Work permit')]),
            ('C', 'Schengen Short-Stay', 'Ninety days in any rolling 180 across the area. Refusals almost always come down to weak proof of ties or purpose.',
             [('Stay', '90 / 180 days'), ('Area', 'Schengen'), ('Purpose', 'Visit · business')]),
        ],
    },
]

# The consultancy process, told per service. The four things the prompt names —
# profile, destination and province, pathway, and the process itself.
HELP_STEPS = [
    ('Profile assessment',
     'We score your profile the way the authorities will — age, qualifications, work history, '
     'language results — and tell you where it actually stands before any fee is discussed.'),
    ('Destination &amp; province selection',
     'Countries and provinces want different occupations at different times. We match your '
     'profile to the places where it is genuinely competitive, not the ones that are popular.'),
    ('Pathway mapping',
     'You get the routes open to you now, and the ones a single change — a language retake, a '
     'skills assessment, six more months of experience — would open next.'),
    ('Documentation &amp; filing',
     'Assessments, language tests, police clearances, and the file itself: assembled, checked '
     'and submitted, with every deadline tracked on our side rather than yours.'),
    ('After the decision',
     'Landing, obligations, dependants and the route onwards — the part most consultancies stop '
     'short of, and the part that decides whether the move actually works.'),
]


# --------------------------------------------------------------------------
# Services — rendering
# --------------------------------------------------------------------------


def render_service(svc, partials):
    band = '\n\n'.join([
        nav_for_page(partials['nav'], has_consultation=True),
        crumbs([('Home', 'hero-full.html'), ('Services', 'services.html'), (svc['short'], None)]),
        page_head(eyebrow='Service', title=svc['title'], lede=svc['lede'], chips=svc['chips']),
    ])
    band = '\n'.join('  ' + line if line.strip() else line for line in band.split('\n'))

    groups = []
    for group in svc['groups']:
        nodes = []
        for name, text, tag in group['nodes']:
            nodes.append(
                f'              <div class="svc-node">\n'
                f'                <b>{name}</b>\n'
                f'                <span>{text}</span>\n'
                f'                <span class="svc-node__tag">{tag}</span>\n'
                f'              </div>')
        groups.append(
            f'            <div class="svc-group reveal">\n'
            f'              <div class="svc-group__head">\n'
            f'                <span class="svc-group__flag">{group["code"]}</span>\n'
            f'                <h3 class="svc-group__name">{group["name"]}</h3>\n'
            f'                <span class="svc-group__count">{len(group["nodes"])} routes</span>\n'
            f'              </div>\n'
            f'              <div class="svc-branch">\n' + '\n'.join(nodes) + '\n'
            f'              </div>\n'
            f'            </div>')

    types = []
    for code, name, text, facts in svc['types']:
        rows = '\n'.join(
            f'              <div class="svc-type__fact"><dt>{k}</dt><dd>{v}</dd></div>'
            for k, v in facts)
        types.append(
            f'          <article class="svc-type reveal">\n'
            f'            <span class="svc-type__code">{code}</span>\n'
            f'            <h3 class="svc-type__name">{name}</h3>\n'
            f'            <p class="svc-type__text">{text}</p>\n'
            f'            <dl class="svc-type__facts">\n{rows}\n            </dl>\n'
            f'          </article>')

    steps = '\n'.join(
        f'          <article class="svc-help__step reveal">\n'
        f'            <h3 class="svc-help__title">{title}</h3>\n'
        f'            <p class="svc-help__text">{text}</p>\n'
        f'          </article>'
        for title, text in HELP_STEPS)

    main = f'''  <main>

    <!-- Visa categories, as a map, against the service photograph -->
    <section class="section-block">
      <div class="wrap">
{block_head('01', 'Visa categories &amp; types', 'The routes this service covers, grouped the way the authorities group them.')}

        <div class="svc-split">
          <div class="svc-tree">
{chr(10).join(groups)}
          </div>

          <figure class="svc-media reveal">
            <img src="{svc['image']}" alt="{svc['alt']}" />
            <figcaption class="svc-media__plate">
              <b>{svc['plate'][0]}</b>
              <span>{svc['plate'][1]}</span>
            </figcaption>
          </figure>
        </div>
      </div>
    </section>

    <!-- Each type, explained -->
    <section class="section-block svc-types-section">
      <div class="wrap">
{block_head('02', 'What each visa type means', 'Plain descriptions of the routes above, and the conditions attached to them.')}

        <div class="svc-types">
{chr(10).join(types)}
        </div>
      </div>
    </section>

    <!-- How we can help -->
    <section class="section-block">
      <div class="wrap">
{block_head('03', 'How we can help', 'The same process on every case, from the first assessment to the year after the decision.')}

        <div class="svc-help">
{steps}
        </div>
      </div>
    </section>

  </main>'''

    return shell(
        title=f'{html.unescape(svc["title"])} — HOF Migration',
        description=html.unescape(svc['card_text']),
        body_class='service-page',
        css=['service-page.css'],
        js=['cta-birds.js', 'feedback-languages.js'],
        band=band,
        main=main,
        partials=partials,
    ).replace('<body class="service-page">',
              f'<body class="service-page" style="--svc-accent:{svc["accent"]}; --svc-tint:{svc["tint"]}">')


def render_services_index(partials):
    band = '\n\n'.join([
        nav_for_page(partials['nav'], has_consultation=True),
        crumbs([('Home', 'hero-full.html'), ('Services', None)]),
        page_head(
            eyebrow='Services',
            title='Immigration &amp; Education<br />Consultancy Services',
            lede=('Five services, each built around a different question: whether you qualify, '
                  'where you would actually be competitive, and what the route looks like once '
                  'the decision is made.'),
            chips=['5 services', 'Canada · Australia · UK · USA · Europe'],
        ),
    ])
    band = '\n'.join('  ' + line if line.strip() else line for line in band.split('\n'))

    cards = []
    for svc in SERVICES:
        cards.append(
            f'          <a class="svc-index__card reveal" href="{svc["slug"]}.html"\n'
            f'             style="--card-bg:{svc["tint"]}; --card-accent:{svc["accent"]}">\n'
            f'            <span class="svc-index__media">\n'
            f'              <img src="{svc["image"]}" alt="{svc["alt"]}" />\n'
            f'            </span>\n'
            f'            <h2 class="svc-index__title">{svc["title"]}</h2>\n'
            f'            <p class="svc-index__text">{svc["card_text"]}</p>\n'
            f'            <span class="svc-index__link">See how we can help</span>\n'
            f'          </a>')

    main = f'''  <main>
    <section class="section-block">
      <div class="wrap">
        <div class="svc-index">
{chr(10).join(cards)}
        </div>
      </div>
    </section>
  </main>'''

    return shell(
        title='Services — HOF Migration',
        description='Skilled migration, study abroad, family sponsorship, U.S. petitions and European residence.',
        body_class='service-page',
        css=['service-page.css'],
        js=['cta-birds.js', 'feedback-languages.js'],
        band=band,
        main=main,
        partials=partials,
    )


# --------------------------------------------------------------------------
# Success stories — data
#
# Ahmed is the story the Home page already carries; his summary is kept word
# for word so the card and the page agree. The other three are placeholders.
# --------------------------------------------------------------------------

STORIES = [
    {
        'slug': 'story-ahmed',
        'name': 'Ahmed',
        'headline': 'Ahmed&rsquo;s Journey to the United States',
        'route': 'Manufacturing Professional &middot; Dubai, UAE &rarr; United States',
        'caption': 'Watch Ahmed&rsquo;s story',
        'excerpt': ('Ahmed had been living and working in Dubai for the past 15 years in the '
                    'manufacturing industry. He had been considering moving to the United States '
                    'and wanted professional guidance on the right migration pathway.'),
        'facts': [('Destination', 'United States'), ('Route', 'EB-2 NIW'),
                  ('From', 'Dubai, UAE'), ('Timeline', '14 months'), ('Outcome', 'Petition approved')],
        'quote': ('I had read everything online and still could not tell which route was mine. '
                  'The first conversation was the first time anyone told me what I did not qualify for.'),
        'prose': [
            ('', 'Ahmed had been living and working in Dubai for the past 15 years in the '
                 'manufacturing industry. He had been considering moving to the United States and '
                 'wanted professional guidance on the right migration pathway. HOF Migration helped '
                 'him understand his options and guided him through the process.'),
            ('Where he started', 'Fifteen years of process engineering, three plant '
                                 'commissionings and a handful of internal awards is a strong record — but it is not '
                                 'a record that speaks for itself on paper. The first work was separating what Ahmed '
                                 'had done from what could be evidenced.'),
            ('Choosing the route', 'An employer-sponsored route would have tied the move to a '
                                   'single company and a queue measured in years. The national interest waiver let him '
                                   'petition on his own, provided the argument held. We tested that argument before '
                                   'committing to it.'),
            ('Building the file', 'Six independent letters, a documented record of the plants his '
                                  'process work had improved, and a written case for why the work mattered beyond his '
                                  'own employer. The petition ran to a little over three hundred pages.'),
            ('Where he is now', 'Ahmed relocated with his family the following year. He is working '
                               'in the same field, in the same role, on the other side of the world.'),
        ],
    },
    {
        'slug': 'story-priya',
        'name': 'Priya',
        'headline': 'Priya&rsquo;s Path to Canadian Permanent Residence',
        'route': 'Software Engineer &middot; Dubai, UAE &rarr; Toronto, Canada',
        'caption': 'Watch Priya&rsquo;s story',
        'excerpt': ('Priya had a competitive Express Entry score that was still short of the cut-off '
                    'in every recent round. Rather than wait, we mapped the provincial streams where '
                    'her occupation was actually in demand.'),
        'facts': [('Destination', 'Canada'), ('Route', 'Express Entry &middot; PNP'),
                  ('From', 'Dubai, UAE'), ('Timeline', '11 months'), ('Outcome', 'Permanent residence')],
        'quote': ('I was twelve points short and had been told to retake my language test again. '
                  'Nobody had mentioned that a province might simply want me.'),
        'prose': [
            ('', 'Priya had spent six years as a backend engineer in Dubai and had entered the '
                 'Express Entry pool on her own. Her score sat consistently below the round '
                 'cut-offs, and the advice she had been given amounted to waiting and retaking '
                 'tests she had already done well in.'),
            ('Reading the score properly', 'A CRS score is not one number — it is a set of levers '
                                           'with very different weights. Hers had one obvious gap and several that were not '
                                           'worth the effort of closing. We said so.'),
            ('The provincial route', 'Two provinces were running targeted draws for her occupation '
                                     'at the time. A nomination adds six hundred points, which ends the question of the '
                                     'cut-off entirely. She was nominated within four months of filing.'),
            ('Where she is now', 'Priya landed in Toronto the following spring and has since '
                                'sponsored her parents for a visit. She is with a fintech company in the same role '
                                'she held in Dubai.'),
        ],
    },
    {
        'slug': 'story-omar',
        'name': 'Omar',
        'headline': 'Omar&rsquo;s Family Reunification in Australia',
        'route': 'Civil Engineer &middot; Sharjah, UAE &rarr; Melbourne, Australia',
        'caption': 'Watch Omar&rsquo;s story',
        'excerpt': ('Omar had held an Australian skilled visa for two years while his wife and '
                    'daughter remained in Sharjah. The partner application had already been refused '
                    'once before he came to us.'),
        'facts': [('Destination', 'Australia'), ('Route', 'Partner visa 309/100'),
                  ('From', 'Sharjah, UAE'), ('Timeline', '16 months'), ('Outcome', 'Visa granted')],
        'quote': ('We had been married for nine years. It had not occurred to me that I would '
                  'need to prove it to somebody who had never met us.'),
        'prose': [
            ('', 'Omar moved to Melbourne on a skilled visa and filed for his wife and daughter '
                 'himself. The application was refused. Nothing about the relationship was in '
                 'doubt — the evidence simply did not establish it in the form the department '
                 'assesses.'),
            ('What went wrong the first time', 'A marriage certificate and a handful of '
                                               'photographs. Genuine, and nowhere near enough. These cases are decided on the '
                                               'four strands the department names, and the first file addressed one of them.'),
            ('Rebuilding the evidence', 'Joint finances going back six years, correspondence, '
                                        'travel records, statements from family on both sides, and a written statement from '
                                        'each of them in their own words. Assembled to be followed by a stranger.'),
            ('Where they are now', 'The visa was granted and the family has been in Melbourne '
                                  'since. Their second child was born there.'),
        ],
    },
    {
        'slug': 'story-fatima',
        'name': 'Fatima',
        'headline': 'Fatima&rsquo;s Student Visa to the United Kingdom',
        'route': 'Graduate Student &middot; Abu Dhabi, UAE &rarr; Manchester, United Kingdom',
        'caption': 'Watch Fatima&rsquo;s story',
        'excerpt': ('Fatima held offers from three universities and had no idea which one served '
                    'her actual plan — which was not the degree, but the two years of work that '
                    'follow it.'),
        'facts': [('Destination', 'United Kingdom'), ('Route', 'Student visa &middot; Graduate Route'),
                  ('From', 'Abu Dhabi, UAE'), ('Timeline', '5 months'), ('Outcome', 'Visa granted')],
        'quote': ('I was choosing a university. It turned out I was choosing what I would be '
                  'allowed to do for the three years after it.'),
        'prose': [
            ('', 'Fatima had three offers and a family decision to make. The question she brought '
                 'was which course was best. The question that mattered was what she wanted to be '
                 'doing in 2030.'),
            ('Choosing backwards', 'Work rights after study are set by the qualification and the '
                                  'institution, not by the subject alone. Once she had decided she wanted to stay and '
                                  'work, two of the three offers stopped being serious options.'),
            ('The financial requirement', 'Maintenance funds must sit in an eligible account for '
                                          'twenty-eight consecutive days, and the single most common refusal we see is a '
                                          'balance that dipped on day nineteen. Hers was planned around that rule.'),
            ('Where she is now', 'Fatima completed her masters in Manchester and is working there '
                                'on the Graduate Route, with a sponsored role under discussion.'),
        ],
    },
]


def story_video(caption, extra_class='', note=None):
    note_html = f'\n            <span class="story-stage__note">{note}</span>' if note else ''
    return (f'          <div class="stories__video{extra_class}">\n'
            f'            <div class="stories__video-noise"></div>\n'
            f'            <button type="button" class="stories__play" aria-label="Play video">\n'
            f'              <svg viewBox="0 0 24 24" fill="#14161a"><path d="M8 5v14l11-7z"/></svg>\n'
            f'            </button>\n'
            f'            <span class="stories__video-caption">{caption}</span>{note_html}\n'
            f'          </div>')


def render_stories_index(partials):
    band = '\n\n'.join([
        nav_for_page(partials['nav'], has_consultation=True),
        crumbs([('Home', 'hero-full.html'), ('Success Stories', None)]),
        page_head(
            eyebrow='Success Stories',
            title='The people behind<br />the applications',
            lede=('Four cases, told as they happened — including the parts that went wrong '
                  'first. Names and details are used with permission.'),
            chips=['4 stories', 'Canada · USA · UK · Australia'],
        ),
    ])
    band = '\n'.join('  ' + line if line.strip() else line for line in band.split('\n'))

    cards = []
    for story in STORIES:
        cards.append(
            f'        <article class="story-card reveal">\n'
            f'{story_video(story["caption"])}\n'
            f'          <div class="story-card__body">\n'
            f'            <span class="story-card__eyebrow">Success Story</span>\n'
            f'            <h2 class="story-card__name">{story["headline"]}</h2>\n'
            f'            <span class="story-card__route">{story["route"]}</span>\n'
            f'            <p class="story-card__text">{story["excerpt"]}</p>\n'
            f'            <a class="story-card__link" href="{story["slug"]}.html">Read Full Story</a>\n'
            f'          </div>\n'
            f'        </article>')

    main = f'''  <main>
    <section class="section-block">
      <div class="wrap">
        <div class="story-list">
{chr(10).join(cards)}
        </div>
      </div>
    </section>
  </main>'''

    return shell(
        title='Success Stories — HOF Migration',
        description='Four migration cases, told as they happened.',
        body_class='story-page',
        css=['stories.css', 'story-page.css'],
        js=['cta-birds.js'],
        band=band,
        main=main,
        partials=partials,
        sections=('expert_cta',),
    )


def render_story(story, partials):
    band = '\n\n'.join([
        nav_for_page(partials['nav'], has_consultation=True),
        crumbs([('Home', 'hero-full.html'), ('Success Stories', 'success-stories.html'),
                (story['name'], None)]),
        page_head(eyebrow='Success Story', title=story['headline'],
                  lede=story['excerpt'], chips=[story['route']]),
    ])
    band = '\n'.join('  ' + line if line.strip() else line for line in band.split('\n'))

    prose = []
    for i, (heading, text) in enumerate(story['prose']):
        if heading:
            prose.append(f'            <h2>{heading}</h2>')
        prose.append(f'            <p>{text}</p>')
        # the quote sits after the opening passage, where it reads as the
        # reason for everything that follows
        if i == 0:
            prose.append(f'            <blockquote class="story-quote">\n'
                         f'              <p>&ldquo;{story["quote"]}&rdquo;</p>\n'
                         f'              <cite>{story["name"]}</cite>\n'
                         f'            </blockquote>')

    facts = '\n'.join(
        f'            <div class="facts__row"><dt>{k}</dt><dd>{v}</dd></div>'
        for k, v in story['facts'])

    main = f'''  <main>

    <section class="section-block section-block--tight">
      <div class="wrap">
        <div class="story-stage reveal">
{story_video(story['caption'], note='Video placeholder')}
        </div>
      </div>
    </section>

    <section class="section-block section-block--tight">
      <div class="wrap">
        <div class="story-body">
          <article class="story-prose reveal">
{chr(10).join(prose)}
          </article>

          <dl class="facts reveal">
            <span class="facts__title">Case at a glance</span>
{facts}
          </dl>
        </div>
      </div>
    </section>

  </main>'''

    return shell(
        title=f'{html.unescape(story["headline"])} — HOF Migration',
        description=html.unescape(story['excerpt'])[:155],
        body_class='story-page',
        css=['stories.css', 'story-page.css'],
        js=['cta-birds.js'],
        band=band,
        main=main,
        partials=partials,
        sections=('expert_cta',),
    )


# --------------------------------------------------------------------------
# About — company, brandmark, and the two sets of people
#
# Every person here is a placeholder. Names, roles and stories are invented
# and are there to carry the layout until real ones arrive.
# --------------------------------------------------------------------------

ABOUT_INTRO = [
    ('HOF Migration is a Dubai consultancy that takes migration cases from the first honest '
     'assessment through to the year after a decision lands. We are ICCRC and MARA certified, '
     'and we work on Canada, Australia, the United Kingdom, the United States and Europe.'),
    ('The firm was built around one observation: most people do not fail because they were '
     'ineligible. They fail because nobody told them, early and plainly, which route was '
     'theirs — and because the file that went in did not say what it needed to say.'),
    ('So the first conversation is an assessment, not a pitch. If the answer is that you should '
     'wait six months, sit a test again, or that we are not the right firm for your case, that '
     'is the answer you get. It costs us work in the short term and it is the only way this '
     'is worth doing.'),
]

ABOUT_STATS = [
    ('6', 'Years advising on migration from the Gulf'),
    ('5', 'Destination systems worked on in-house'),
    ('2', 'Regulatory bodies we are certified by — ICCRC and MARA'),
    ('1', 'Assessment before any engagement, always'),
]

LEADERSHIP = [
    {
        'slug': 'team-hana-al-mansouri', 'name': 'Hana Al Mansouri', 'initials': 'HA',
        'role': 'Chief Executive Officer &amp; Co-Founder', 'mono': '#2e564d',
        'short': ('Founded the firm after a decade of watching good applications fail on bad '
                  'advice. Sets what the firm will and will not take on.'),
        'facts': [('Role', 'CEO &amp; Co-Founder'), ('Based in', 'Dubai, UAE'),
                  ('Focus', 'Practice standards'), ('Languages', 'Arabic, English'), ('Joined', '2020 — founding')],
        'prose': [
            ('', 'Hana spent ten years inside immigration practice before founding HOF Migration, '
                 'most of it watching capable applicants lose years to advice that was confident '
                 'and wrong.'),
            ('Why the firm exists', 'The pattern was always the same: someone had been told they '
                                    'qualified, paid for a filing, and found out eighteen months later that the route '
                                    'had never been open to them. Hana built the firm around refusing that first '
                                    'conversation — the one where a fee is quoted before a profile is read.'),
            ('What she does here', 'She sets the assessment standard every case is held to, and '
                                   'she signs off on the cases the firm declines, which she considers the more '
                                   'important half of the job.'),
        ],
    },
    {
        'slug': 'team-omar-farouk', 'name': 'Omar Farouk', 'initials': 'OF',
        'role': 'Co-Founder &amp; Managing Director', 'mono': '#406d63',
        'short': ('Runs the practice day to day. Owns the part of the process where a case stops '
                  'being advice and becomes a filed file.'),
        'facts': [('Role', 'Co-Founder &amp; MD'), ('Based in', 'Dubai, UAE'),
                  ('Focus', 'Case delivery'), ('Languages', 'Arabic, English, French'), ('Joined', '2020 — founding')],
        'prose': [
            ('', 'Omar co-founded the firm and runs it day to day. His responsibility is the '
                 'distance between a good assessment and a filed application, which is where most '
                 'consultancies quietly lose their clients.'),
            ('On deadlines', 'Every deadline on a case sits on the firm’s side of the table, not '
                             'the client’s. Police clearances expire, language results age out, and pools close '
                             'on a schedule nobody is reminded about. Tracking that is the job.'),
            ('Background', 'Fifteen years in operations across professional services in the Gulf '
                           'before moving into migration practice.'),
        ],
    },
    {
        'slug': 'team-priya-nair', 'name': 'Priya Nair', 'initials': 'PN',
        'role': 'Director, Skilled Migration', 'mono': '#518579',
        'short': ('Leads the Canada and Australia practice. Reads points systems for a living and '
                  'is unsentimental about scores.'),
        'facts': [('Role', 'Director, Skilled Migration'), ('Based in', 'Dubai, UAE'),
                  ('Focus', 'Canada &amp; Australia'), ('Languages', 'English, Hindi, Malayalam'), ('Joined', '2021')],
        'prose': [
            ('', 'Priya leads the skilled migration practice — Express Entry, the provincial '
                 'streams, and the Australian subclasses.'),
            ('On honest scoring', 'A points score is a set of levers with very different weights, '
                                  'and most of them are not worth pulling. Telling someone which of their gaps to '
                                  'ignore saves them more time than telling them which to close.'),
            ('Background', 'Registered practitioner with eight years on Canadian and Australian '
                           'skilled cases, including three years reading provincial nomination streams.'),
        ],
    },
    {
        'slug': 'team-daniel-okonkwo', 'name': 'Daniel Okonkwo', 'initials': 'DO',
        'role': 'Director, U.S. Petitions', 'mono': '#66998d',
        'short': ('Builds the evidence files behind national interest waivers and extraordinary '
                  'ability petitions. Writes cases, not forms.'),
        'facts': [('Role', 'Director, U.S. Petitions'), ('Based in', 'Dubai, UAE'),
                  ('Focus', 'EB-2 NIW, EB-1A'), ('Languages', 'English'), ('Joined', '2021')],
        'prose': [
            ('', 'Daniel runs the United States practice, where the work is closer to building an '
                 'argument than completing an application.'),
            ('On petitions', 'A national interest waiver is won or lost on whether a stranger, '
                             'reading three hundred pages cold, can follow why the work matters. That is a '
                             'drafting problem before it is a legal one.'),
            ('Background', 'Nine years on employment-based petitions, previously with a U.S. firm '
                           'handling extraordinary ability and national interest cases.'),
        ],
    },
    {
        'slug': 'team-layla-haddad', 'name': 'Layla Haddad', 'initials': 'LH',
        'role': 'Director, Client Practice', 'mono': '#8daba4',
        'short': ('Owns the client experience end to end, and the firm’s rule that nobody is '
                  'left wondering what happens next.'),
        'facts': [('Role', 'Director, Client Practice'), ('Based in', 'Dubai, UAE'),
                  ('Focus', 'Client experience'), ('Languages', 'Arabic, English'), ('Joined', '2022')],
        'prose': [
            ('', 'Layla is responsible for what it actually feels like to be a client here, which '
                 'she treats as a measurable thing rather than a sentiment.'),
            ('The standing rule', 'No client should ever have to ask what happens next. If a case '
                                  'is waiting on a government queue for four months, that is said plainly, along with '
                                  'the date we will next have something to report.'),
            ('Background', 'A decade in client services across legal and financial practices in '
                           'the Gulf.'),
        ],
    },
]

CORE_TEAM = [
    {
        'slug': 'team-yusuf-rahman', 'name': 'Yusuf Rahman', 'initials': 'YR',
        'role': 'Senior Case Manager', 'mono': '#2e564d',
        'short': 'Carries skilled migration files from assessment through to decision.',
        'facts': [('Role', 'Senior Case Manager'), ('Based in', 'Dubai, UAE'),
                  ('Focus', 'Canada — Express Entry'), ('Languages', 'Arabic, English, Urdu'), ('Joined', '2022')],
        'prose': [
            ('', 'Yusuf manages skilled migration files end to end, which means he is the person '
                 'who notices that a language result expires three weeks before an expected draw.'),
            ('What the job is', 'Most of case management is arithmetic with dates. The rest is '
                                'making sure a document that was correct in March is still correct in September.'),
        ],
    },
    {
        'slug': 'team-mariam-saleh', 'name': 'Mariam Saleh', 'initials': 'MS',
        'role': 'Case Manager, Family &amp; Partner', 'mono': '#406d63',
        'short': 'Handles sponsorship and partner cases, and the evidence they turn on.',
        'facts': [('Role', 'Case Manager'), ('Based in', 'Dubai, UAE'),
                  ('Focus', 'Family &amp; partner visas'), ('Languages', 'Arabic, English'), ('Joined', '2023')],
        'prose': [
            ('', 'Mariam works on family and partner cases, the part of the practice where the '
                 'facts are never in doubt and the evidence usually is.'),
            ('On relationship evidence', 'Asking a couple to prove a marriage they have lived in '
                                         'for nine years is an uncomfortable conversation. Having it early is what keeps it '
                                         'from becoming a refusal later.'),
        ],
    },
    {
        'slug': 'team-arjun-mehta', 'name': 'Arjun Mehta', 'initials': 'AM',
        'role': 'Education Counsellor', 'mono': '#518579',
        'short': 'Matches students to courses, institutions and the work rights that follow.',
        'facts': [('Role', 'Education Counsellor'), ('Based in', 'Dubai, UAE'),
                  ('Focus', 'Study abroad'), ('Languages', 'English, Hindi'), ('Joined', '2023')],
        'prose': [
            ('', 'Arjun advises students choosing between offers, which is rarely a choice about '
                 'the course.'),
            ('Choosing backwards', 'What a student can do in the three years after graduating is '
                                   'set by the institution and the qualification. That decision is being made when the '
                                   'offer is accepted, whether or not anyone realises it.'),
        ],
    },
    {
        'slug': 'team-sara-abdullah', 'name': 'Sara Abdullah', 'initials': 'SA',
        'role': 'Documentation Specialist', 'mono': '#66998d',
        'short': 'Assembles and checks the file itself, down to the certified translations.',
        'facts': [('Role', 'Documentation Specialist'), ('Based in', 'Dubai, UAE'),
                  ('Focus', 'File preparation'), ('Languages', 'Arabic, English'), ('Joined', '2023')],
        'prose': [
            ('', 'Sara prepares the files that go in — assessments, clearances, translations and '
                 'the order they are presented in.'),
            ('Why it matters', 'A complete file that is hard to read is still a hard file to '
                               'approve. Sequence and labelling are not administrative details.'),
        ],
    },
    {
        'slug': 'team-khalid-nasser', 'name': 'Khalid Nasser', 'initials': 'KN',
        'role': 'Client Liaison', 'mono': '#8daba4',
        'short': 'The person clients actually reach, and the one who chases what is outstanding.',
        'facts': [('Role', 'Client Liaison'), ('Based in', 'Dubai, UAE'),
                  ('Focus', 'Client communication'), ('Languages', 'Arabic, English'), ('Joined', '2024')],
        'prose': [
            ('', 'Khalid is the first person most clients speak to and the one who follows up '
                 'when something is outstanding.'),
            ('On chasing', 'A case stalled for three weeks waiting on one document is the most '
                           'avoidable delay in this business, and avoiding it is somebody’s actual job.'),
        ],
    },
]


def brandmark_svg():
    """The lockup, inlined so its three parts can be animated separately."""
    svg = (ROOT / 'assets' / 'icons-v2' / 'logo-brand.svg').read_text(encoding='utf-8').strip()
    # drawn white here: the stage is dark in both themes
    svg = svg.replace('fill="black"', 'fill="#ffffff"')
    # The three drawn elements, in document order: mark, stem, wordmark. Split
    # rather than replace-first three times — a replacement leaves "<path "
    # intact, so the next pass would land on the same element again.
    parts = svg.split('<path ')
    if len(parts) != 4:
        sys.exit(f'logo-brand.svg: expected 3 paths, found {len(parts) - 1}')
    svg = parts[0] + ''.join(
        f'<path class="{cls}" ' + part
        for cls, part in zip(('bm-mark', 'bm-stem', 'bm-word'), parts[1:]))
    svg = svg.replace('<svg ', '<svg aria-hidden="true" ', 1)
    return '\n'.join('          ' + line for line in svg.split('\n'))


def person_card(person):
    return (f'          <a class="person reveal" href="{person["slug"]}.html"'
            f' style="--mono:{person["mono"]}">\n'
            f'            <span class="person__mono" aria-hidden="true">{person["initials"]}</span>\n'
            f'            <span class="person__role">{person["role"]}</span>\n'
            f'            <h3 class="person__name">{person["name"]}</h3>\n'
            f'            <p class="person__text">{person["short"]}</p>\n'
            f'            <span class="person__link">Read full profile</span>\n'
            f'          </a>')


def render_about(partials):
    band = '\n\n'.join([
        nav_for_page(partials['nav'], has_consultation=False),
        crumbs([('Home', 'hero-full.html'), ('About Us', None)]),
        page_head(
            eyebrow='About Us',
            title='A consultancy built<br />on the honest answer',
            lede=('HOF Migration advises on skilled migration, study, family reunification and '
                  'investor routes from Dubai — and turns down the cases it cannot genuinely '
                  'help with.'),
            chips=['Founded 2020', 'Dubai, UAE', 'ICCRC &amp; MARA certified'],
        ),
    ])
    band = '\n'.join('  ' + line if line.strip() else line for line in band.split('\n'))

    stats = '\n'.join(
        f'          <div class="about-stat"><b>{value}</b><span>{label}</span></div>'
        for value, label in ABOUT_STATS)
    paras = '\n'.join(f'            <p>{p}</p>' for p in ABOUT_INTRO)

    main = f'''  <main>

    <!-- Company -->
    <section class="section-block">
      <div class="wrap">
        <div class="about-intro reveal">
          <h2 class="about-intro__title">Migration advice that starts with what you do not qualify for.</h2>
          <div class="about-intro__body">
{paras}
          </div>
        </div>

        <div class="about-stats reveal">
{stats}
        </div>
      </div>
    </section>

    <!-- The mark -->
    <section class="section-block section-block--tight">
      <div class="wrap">
        <div class="brandmark reveal" data-brandmark>
          <span class="brandmark__glow" aria-hidden="true"></span>
          <span class="brandmark__ring" aria-hidden="true"></span>
          <div class="brandmark__lockup">
{brandmark_svg()}
          </div>
          <span class="brandmark__sheen" aria-hidden="true"></span>
          <span class="brandmark__caption">Established in Dubai &middot; 2020</span>
        </div>
      </div>
    </section>

    <!-- Leadership -->
    <section class="section-block" id="leadership">
      <div class="wrap">
{block_head('01', 'Leadership', 'The people accountable for what the firm takes on and how it is run.')}

        <div class="people">
{chr(10).join(person_card(p) for p in LEADERSHIP)}
        </div>
      </div>
    </section>

    <!-- Core team -->
    <section class="section-block" id="team">
      <div class="wrap">
{block_head('02', 'Our Core Team', 'The people who carry the cases day to day.')}

        <div class="people">
{chr(10).join(person_card(p) for p in CORE_TEAM)}
        </div>
      </div>
    </section>

  </main>'''

    return shell(
        title='About Us — HOF Migration',
        description='A Dubai migration consultancy, its leadership and its core team.',
        body_class='about-page',
        css=['about.css'],
        js=[],
        band=band,
        main=main,
        partials=partials,
        sections=(),
    )


def render_person(person, partials):
    band = '\n\n'.join([
        nav_for_page(partials['nav'], has_consultation=False),
        crumbs([('Home', 'hero-full.html'), ('About Us', 'about.html'), (person['name'], None)]),
        f'''      <div class="person-page__head">
        <span class="person__mono" style="--mono:{person['mono']}" aria-hidden="true">{person['initials']}</span>
        <div class="page-head">
          <span class="page-head__eyebrow">{person['role']}</span>
          <h1 class="page-head__title">{person['name']}</h1>
          <p class="page-head__lede">{person['short']}</p>
        </div>
      </div>''',
    ])
    band = '\n'.join('  ' + line if line.strip() else line for line in band.split('\n'))

    prose = []
    for heading, text in person['prose']:
        if heading:
            prose.append(f'            <h2>{heading}</h2>')
        prose.append(f'            <p>{text}</p>')

    facts = '\n'.join(
        f'            <div class="facts__row"><dt>{k}</dt><dd>{v}</dd></div>'
        for k, v in person['facts'])

    main = f'''  <main>
    <section class="section-block">
      <div class="wrap">
        <div class="person-body">
          <article class="person-prose reveal">
{chr(10).join(prose)}
          </article>

          <dl class="facts reveal">
            <span class="facts__title">At a glance</span>
{facts}
          </dl>
        </div>
      </div>
    </section>
  </main>'''

    return shell(
        title=f'{html.unescape(person["name"])} — HOF Migration',
        description=html.unescape(f'{person["name"]}, {person["role"]} at HOF Migration.'),
        body_class='about-page',
        css=['about.css'],
        js=[],
        band=band,
        main=main,
        partials=partials,
        sections=(),
    )


# --------------------------------------------------------------------------


def main():
    partials = load_partials()
    written = []

    out = ROOT / 'services.html'
    out.write_text(render_services_index(partials), encoding='utf-8')
    written.append(out.name)

    for svc in SERVICES:
        out = ROOT / f'{svc["slug"]}.html'
        out.write_text(render_service(svc, partials), encoding='utf-8')
        written.append(out.name)

    out = ROOT / 'success-stories.html'
    out.write_text(render_stories_index(partials), encoding='utf-8')
    written.append(out.name)

    for story in STORIES:
        out = ROOT / f'{story["slug"]}.html'
        out.write_text(render_story(story, partials), encoding='utf-8')
        written.append(out.name)

    out = ROOT / 'about.html'
    out.write_text(render_about(partials), encoding='utf-8')
    written.append(out.name)

    for person in LEADERSHIP + CORE_TEAM:
        out = ROOT / f'{person["slug"]}.html'
        out.write_text(render_person(person, partials), encoding='utf-8')
        written.append(out.name)

    print('\n'.join(written))


if __name__ == '__main__':
    main()
